#!/bin/sh

print_usage() {
  echo "Usage: $(basename $0) <container id/name> [{command:-$SHELL} [argments...]]"
}

ID="$1"; shift
if [ -z "$ID" ] ; then
  print_usage >&2
  exit 1
fi

CID=$(docker inspect --format '{{.Id}}' "$ID" 2> /dev/null)
if [ -z "$CID" ] ; then
  print_usage >&2
  exit 1
fi

CMD="${1:-$SHELL}"; shift

ARGS=""
for arg in "$@"; do
  ARGS="${ARGS}${arg// /\\ } "
done
ARGS=${ARGS%%?}

echo "cd /var/lib/docker/execdriver/native/$CID && nsinit exec -- $CMD $ARGS"
sudo sh -c "cd /var/lib/docker/execdriver/native/$CID && nsinit exec -- $CMD $ARGS"
