#!/bin/sh

print_usage() {
  echo "Usage: $(basename $0) <container id/name> [{command:-$SHELL} [argments...]]"
}

ID="$1"
if [ -z "$ID" ] ; then
  print_usage >&2
  exit 1
fi
shift

CID=$(docker inspect --format '{{.Id}}' "$ID" 2> /dev/null)
if [ -z "$CID" ] ; then
  echo "$ID: no such container is running" >&2
  exit 1
fi

IS_RUNNING=$(docker inspect --format '{{.State.Running}}' "$ID" 2> /dev/null)
if [ "$IS_RUNNING" != "true" ] ; then
  echo "$ID: no such container is running" >&2
  exit 1
fi

CMD="${1:-$SHELL}"; [ ! -z "$1" ] && shift

echo data_path="/var/lib/docker/execdriver/native/$CID" nsinit exec -- "$CMD" "$@"
sudo data_path="/var/lib/docker/execdriver/native/$CID" nsinit exec -- "$CMD" "$@"
